import { BentoCard, CardSize } from '../types';

export interface Template {
  name: string;
  emoji: string;
  description: string;
  category: 'portfolio' | 'social' | 'business' | 'creative' | 'ecommerce' | 'personal';
  cards: BentoCard[];
}

export const templates: Template[] = [
  {
    name: 'Portfolio Pro',
    emoji: '✨',
    description: 'Professional portfolio showcase with featured work',
    category: 'portfolio',
    cards: [
      { 
        id: '1', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 0, 
        backgroundColor: '#1f2937', 
        text: 'Sarah Chen', 
        subtitle: 'Creative Designer',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 24,
      },
      { 
        id: '2', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 0, 
        backgroundImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop',
        text: '',
      },
      { 
        id: '3', 
        size: 'square' as CardSize, 
        x: 6, 
        y: 0,
        backgroundStyle: 'border' as const,
        borderColor: '#ec4899',
        borderWidth: 3,
        text: 'UI/UX',
        subtitle: 'Design',
        textColor: '#ec4899',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '4', 
        size: 'portrait' as CardSize, 
        x: 8, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400',
        text: '',
      },
      { 
        id: '5', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 0,
        backgroundColor: '#60a5fa',
        text: '5+',
        subtitle: 'Years',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 24,
      },
      { 
        id: '6', 
        size: 'large' as CardSize, 
        x: 0, 
        y: 2,
        backgroundImage: 'https://images.unsplash.com/photo-1634942537034-2531766767d1?w=600',
        text: 'Featured Project',
        subtitle: 'Award-winning design',
        textColor: '#ffffff',
        textAlignment: 'left' as const,
        verticalAlignment: 'bottom' as const,
        fontSize: 22,
      },
      { 
        id: '7', 
        size: 'wide' as CardSize, 
        x: 4, 
        y: 2,
        backgroundColor: '#fbbf24',
        text: 'Brand Identity • Web Design • Mobile Apps',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 14,
      },
      { 
        id: '10', 
        size: 'wide' as CardSize, 
        x: 4, 
        y: 4,
        backgroundStyle: 'border' as const,
        borderColor: '#34d399',
        borderWidth: 2,
        text: '📧 hello@sarahchen.design',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 16,
      },
      { 
        id: '11', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 2,
        backgroundColor: '#10b981',
        text: 'Available',
        subtitle: 'For new projects',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '12', 
        size: 'wide' as CardSize, 
        x: 8, 
        y: 4,
        backgroundColor: '#6366f1',
        text: 'Let\'s Work Together',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
    ],
  },
  {
    name: 'Social Links',
    emoji: '🔗',
    description: 'Modern link-in-bio with social media connections',
    category: 'social',
    cards: [
      { 
        id: '1', 
        size: 'large' as CardSize, 
        x: 0, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=600',
        text: '@alexmorgan',
        subtitle: 'Content Creator',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'bottom' as const,
        fontSize: 28,
      },
      { 
        id: '2', 
        size: 'wide' as CardSize, 
        x: 4, 
        y: 0,
        backgroundColor: '#1f2937',
        text: 'GitHub',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '3', 
        size: 'square' as CardSize, 
        x: 8, 
        y: 0,
        backgroundColor: '#60a5fa',
        text: 'Twitter',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '4', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 0,
        backgroundColor: '#ec4899',
        text: 'Instagram',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 16,
      },
      { 
        id: '5', 
        size: 'wide' as CardSize, 
        x: 4, 
        y: 2,
        backgroundColor: '#a78bfa',
        text: 'LinkedIn',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '6', 
        size: 'square' as CardSize, 
        x: 8, 
        y: 2,
        backgroundColor: '#fbbf24',
        text: 'YouTube',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '7', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 2,
        backgroundColor: '#34d399',
        text: 'Spotify',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '8', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 4,
        backgroundStyle: 'border' as const,
        borderColor: '#ec4899',
        borderWidth: 3,
        text: 'Newsletter',
        textColor: '#ec4899',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '9', 
        size: 'wide' as CardSize, 
        x: 4, 
        y: 4,
        backgroundColor: '#f87171',
        text: 'Portfolio',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '10', 
        size: 'wide' as CardSize, 
        x: 8, 
        y: 4,
        backgroundStyle: 'border' as const,
        borderColor: '#60a5fa',
        borderWidth: 3,
        text: 'Contact Me',
        textColor: '#60a5fa',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
    ],
  },
  {
    name: 'Photography',
    emoji: '📸',
    description: 'Stunning photography portfolio with gallery layout',
    category: 'creative',
    cards: [
      { 
        id: '1', 
        size: 'square' as CardSize, 
        x: 0, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=400',
        text: '',
      },
      { 
        id: '2', 
        size: 'wide' as CardSize, 
        x: 2, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
        text: '',
      },
      { 
        id: '3', 
        size: 'sqaure' as CardSize, 
        x: 6, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=400',
        text: '',
      },
      { 
        id: '4', 
        size: 'square' as CardSize, 
        x: 8, 
        y: 0,
        backgroundColor: '#1f2937',
        text: 'Emma',
        subtitle: 'Wilson',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 24,
      },
      { 
        id: '5', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 0,
        backgroundStyle: 'border' as const,
        borderColor: '#fbbf24',
        borderWidth: 3,
        text: 'Travel',
        subtitle: 'Photography',
        textColor: '#fbbf24',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 16,
      },
      { 
        id: '6', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 2,
        backgroundImage: 'https://images.unsplash.com/photo-1511593358241-7eea1f3c84e5?w=600',
        text: '',
      },
      { 
        id: '7', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 2,
        backgroundColor: '#60a5fa',
        text: '50+',
        subtitle: 'Countries',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '8', 
        size: 'square' as CardSize, 
        x: 6, 
        y: 2,
        backgroundImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400',
        text: '',
      },
      { 
        id: '9', 
        size: 'wide' as CardSize, 
        x: 8, 
        y: 2,
        backgroundImage: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600',
        text: 'Landscapes',
        textColor: '#ffffff',
        textAlignment: 'left' as const,
        verticalAlignment: 'bottom' as const,
        fontSize: 22,
      },
      { 
        id: '10', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 4,
        backgroundColor: '#ec4899',
        text: 'Book a Session',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '11', 
        size: 'wide' as CardSize, 
        x: 4, 
        y: 4,
        backgroundStyle: 'border' as const,
        borderColor: '#34d399',
        borderWidth: 2,
        text: '📧 emma@photos.com',
        textColor: '#34d399',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 16,
      },
      { 
        id: '12', 
        size: 'wide' as CardSize, 
        x: 8, 
        y: 4,
        backgroundColor: '#fbbf24',
        text: 'Portfolio',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
    ],
  },
  {
    name: 'Design Studio',
    emoji: '🎨',
    description: 'Creative agency showcase with modern aesthetics',
    category: 'business',
    cards: [
      { 
        id: '1', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 0,
        backgroundColor: '#a78bfa',
        text: 'PIXEL STUDIO',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 26,
      },
      { 
        id: '2', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 0,
        backgroundStyle: 'border' as const,
        borderColor: '#a78bfa',
        borderWidth: 3,
        text: 'Branding',
        textColor: '#a78bfa',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '3', 
        size: 'portrait' as CardSize, 
        x: 6, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400',
        text: '',
      },
      { 
        id: '4', 
        size: 'large' as CardSize, 
        x: 8, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=600',
        text: 'Recent Work',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'bottom' as const,
        fontSize: 24,
      },
      { 
        id: '5', 
        size: 'square' as CardSize, 
        x: 0, 
        y: 2,
        backgroundColor: '#fbbf24',
        text: 'Web',
        subtitle: 'Design',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '6', 
        size: 'square' as CardSize, 
        x: 2, 
        y: 2,
        backgroundColor: '#34d399',
        text: 'Mobile',
        subtitle: 'Apps',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '7', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 2,
        backgroundColor: '#ec4899',
        text: 'Logo',
        subtitle: 'Design',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '8', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 4,
        backgroundColor: '#1f2937',
        text: 'Let\'s Create Something Amazing',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '9', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 4,
        backgroundColor: '#60a5fa',
        text: '200+',
        subtitle: 'Clients',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '10', 
        size: 'square' as CardSize, 
        x: 6, 
        y: 4,
        backgroundStyle: 'border' as const,
        borderColor: '#ec4899',
        borderWidth: 3,
        text: 'Contact',
        textColor: '#ec4899',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '11', 
        size: 'square' as CardSize, 
        x: 8, 
        y: 4,
        backgroundImage: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400',
        text: '',
      },
      { 
        id: '12', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 4,
        backgroundImage: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400',
        text: '',
      },
    ],
  },
  {
    name: 'Product Showcase',
    emoji: '🛍️',
    description: 'E-commerce product display with promotional elements',
    category: 'ecommerce',
    cards: [
      { 
        id: '1', 
        size: 'large' as CardSize, 
        x: 0, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
        text: 'NEW COLLECTION',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'top' as const,
        fontSize: 28,
      },
      { 
        id: '2', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 0,
        backgroundColor: '#1f2937',
        text: '50%',
        subtitle: 'OFF',
        textColor: '#fbbf24',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 32,
      },
      { 
        id: '3', 
        size: 'portrait' as CardSize, 
        x: 6, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
        text: '',
      },
      { 
        id: '4', 
        size: 'square' as CardSize, 
        x: 8, 
        y: 0,
        backgroundColor: '#ec4899',
        text: 'Free',
        subtitle: 'Shipping',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '5', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400',
        text: '',
      },
      { 
        id: '6', 
        size: 'square' as CardSize, 
        x: 8, 
        y: 4,
        backgroundColor: '#fbbf24',
        text: '4.9★',
        subtitle: 'Rated',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 24,
      },
      { 
        id: '7', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 4,
        backgroundColor: '#34d399',
        text: 'Eco',
        subtitle: 'Friendly',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '8', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 2,
        backgroundImage: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400',
        text: '',
      },
      { 
        id: '10', 
        size: 'square' as CardSize, 
        x: 8, 
        y: 2,
        backgroundStyle: 'border' as const,
        borderColor: '#60a5fa',
        borderWidth: 3,
        text: 'Premium',
        subtitle: 'Quality',
        textColor: '#60a5fa',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '11', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 2,
        backgroundColor: '#a78bfa',
        text: '2K+',
        subtitle: 'Reviews',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '12', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 4,
        backgroundColor: '#60a5fa',
        text: 'Shop Now',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 24,
      },
      { 
        id: '13', 
        size: 'wide' as CardSize, 
        x: 4, 
        y: 4,
        backgroundColor: '#ec4899',
        text: 'Limited Time Offer',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
    ],
  },
  {
    name: 'Developer Card',
    emoji: '💻',
    description: 'Tech-focused portfolio for developers and engineers',
    category: 'portfolio',
    cards: [
      { 
        id: '1', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 0,
        backgroundColor: '#0f172a',
        text: 'John Developer',
        subtitle: 'Full Stack Engineer',
        textColor: '#22d3ee',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 24,
      },
      { 
        id: '2', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 0,
        backgroundStyle: 'border' as const,
        borderColor: '#22d3ee',
        borderWidth: 3,
        text: 'React',
        subtitle: 'TypeScript',
        textColor: '#22d3ee',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '3', 
        size: 'square' as CardSize, 
        x: 6, 
        y: 0,
        backgroundColor: '#10b981',
        text: 'Node.js',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '4', 
        size: 'portrait' as CardSize, 
        x: 8, 
        y: 0,
        backgroundColor: '#1e293b',
        text: '10+',
        subtitle: 'Years',
        textColor: '#22d3ee',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 28,
      },
      { 
        id: '5', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 0,
        backgroundStyle: 'border' as const,
        borderColor: '#f59e0b',
        borderWidth: 3,
        text: 'AWS',
        textColor: '#f59e0b',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '6', 
        size: 'large' as CardSize, 
        x: 0, 
        y: 2,
        backgroundColor: '#1e293b',
        text: 'Open Source',
        subtitle: '50+ repos • 1K+ stars',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 22,
      },
      { 
        id: '7', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 2,
        backgroundStyle: 'border' as const,
        borderColor: '#8b5cf6',
        borderWidth: 3,
        text: 'GitHub',
        subtitle: '@johndev',
        textColor: '#8b5cf6',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '8', 
        size: 'square' as CardSize, 
        x: 6, 
        y: 2,
        backgroundColor: '#f59e0b',
        text: 'Fast',
        subtitle: '& Clean',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '9', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 2,
        backgroundColor: '#6366f1',
        text: 'Docker',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '11', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 4,
        backgroundColor: '#0f172a',
        text: 'Hire Me',
        subtitle: 'Available for freelance',
        textColor: '#22d3ee',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '12', 
        size: 'wide' as CardSize, 
        x: 6, 
        y: 4,
        backgroundColor: '#22d3ee',
        text: 'Contact',
        subtitle: 'john@dev.com',
        textColor: '#0f172a',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '13', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 4,
        backgroundColor: '#10b981',
        text: 'Portfolio',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
    ],
  },
  {
    name: 'Minimalist Pro',
    emoji: '⚪',
    description: 'Clean and minimalist design with elegant typography',
    category: 'personal',
    cards: [
      { 
        id: '1', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 0,
        backgroundColor: '#ffffff',
        backgroundStyle: 'border' as const,
        borderColor: '#1f2937',
        borderWidth: 2,
        text: 'Jane Smith',
        subtitle: 'Minimalist Designer',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 28,
      },
      { 
        id: '2', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 0,
        backgroundColor: '#1f2937',
        text: 'Less',
        subtitle: 'Is More',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '3', 
        size: 'portrait' as CardSize, 
        x: 6, 
        y: 0,
        backgroundColor: '#f3f4f6',
        text: 'Design',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 24,
        textOrientation: 'vertical' as const,
      },
      { 
        id: '4', 
        size: 'square' as CardSize, 
        x: 8, 
        y: 0,
        backgroundStyle: 'border' as const,
        borderColor: '#1f2937',
        borderWidth: 2,
        text: 'Clean',
        subtitle: 'Simple',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '5', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 0,
        backgroundColor: '#1f2937',
        text: '✦',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 48,
      },
      { 
        id: '6', 
        size: 'square' as CardSize, 
        x: 0, 
        y: 2,
        backgroundColor: '#f3f4f6',
        text: 'Type',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '7', 
        size: 'square' as CardSize, 
        x: 2, 
        y: 2,
        backgroundColor: '#1f2937',
        text: 'B/W',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '8', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 2,
        backgroundStyle: 'border' as const,
        borderColor: '#1f2937',
        borderWidth: 2,
        text: 'Grid',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '10', 
        size: 'wide' as CardSize, 
        x: 8, 
        y: 2,
        backgroundColor: '#f3f4f6',
        text: 'Portfolio',
        subtitle: 'Selected works',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '11', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 4,
        backgroundStyle: 'border' as const,
        borderColor: '#1f2937',
        borderWidth: 2,
        text: 'Contact',
        subtitle: 'hello@janesmith.com',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '12', 
        size: 'wide' as CardSize, 
        x: 4, 
        y: 4,
        backgroundColor: '#1f2937',
        text: 'Simplicity',
        subtitle: 'Ultimate sophistication',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '13', 
        size: 'wide' as CardSize, 
        x: 8, 
        y: 4,
        backgroundColor: '#f3f4f6',
        text: 'Available',
        subtitle: 'For new projects',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
    ],
  },
  {
    name: 'Vibrant Creator',
    emoji: '🌈',
    description: 'Colorful and energetic layout for creative professionals',
    category: 'creative',
    cards: [
      { 
        id: '1', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 0,
        backgroundImage: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=600',
        text: 'Creative Studio',
        subtitle: 'Bold Designs',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 24,
      },
      { 
        id: '2', 
        size: 'square' as CardSize, 
        x: 4, 
        y: 0,
        backgroundColor: '#ff006e',
        text: '⚡',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 48,
      },
      { 
        id: '3', 
        size: 'square' as CardSize, 
        x: 6, 
        y: 0,
        backgroundColor: '#fb5607',
        text: '🎨',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 48,
      },
      { 
        id: '4', 
        size: 'portrait' as CardSize, 
        x: 8, 
        y: 0,
        backgroundColor: '#ffbe0b',
        text: 'Color',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 28,
        textOrientation: 'vertical' as const,
      },
      { 
        id: '5', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 0,
        backgroundColor: '#8338ec',
        text: '✨',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 48,
      },
      { 
        id: '6', 
        size: 'square' as CardSize, 
        x: 0, 
        y: 2,
        backgroundColor: '#3a86ff',
        text: '💙',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 48,
      },
      { 
        id: '7', 
        size: 'wide' as CardSize, 
        x: 2, 
        y: 2,
        backgroundImage: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600',
        text: 'Featured Work',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'bottom' as const,
        fontSize: 22,
      },
      { 
        id: '8', 
        size: 'square' as CardSize, 
        x: 6, 
        y: 2,
        backgroundColor: '#06ffa5',
        text: '🌟',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 48,
      },
      { 
        id: '9', 
        size: 'square' as CardSize, 
        x: 10, 
        y: 2,
        backgroundColor: '#8338ec',
        text: '500+',
        subtitle: 'Projects',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 24,
      },
      { 
        id: '10', 
        size: 'wide' as CardSize, 
        x: 0, 
        y: 4,
        backgroundColor: '#ff006e',
        text: 'Let\'s Collaborate',
        textColor: '#ffffff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 20,
      },
      { 
        id: '11', 
        size: 'wide' as CardSize, 
        x: 4, 
        y: 4,
        backgroundStyle: 'border' as const,
        borderColor: '#3a86ff',
        borderWidth: 4,
        text: 'Get in Touch',
        subtitle: 'hello@creative.studio',
        textColor: '#3a86ff',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 18,
      },
      { 
        id: '12', 
        size: 'wide' as CardSize, 
        x: 8, 
        y: 4,
        backgroundColor: '#ffbe0b',
        text: '5.0 ⭐',
        subtitle: 'Rating',
        textColor: '#1f2937',
        textAlignment: 'center' as const,
        verticalAlignment: 'center' as const,
        fontSize: 24,
      },
    ],
  },
];

export const getTemplatesByCategory = (category: Template['category']) => {
  return templates.filter(t => t.category === category);
};

export const getTemplateByName = (name: string) => {
  return templates.find(t => t.name === name);
};
